name: Continuous Integration Build

on: [push, pull_request]

jobs:
  build_java8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml

  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  quality:
    needs: [build_java8, build_java11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Sonar analysis
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: |
          mvn verify sonar:sonar -Pcoverage -Dsonar.projectKey=smallrye_smallrye-reactive-messaging -Dsonar.projectName="SmallRye Reactive Messaging" -Dsonar.organization=smallrye -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN


